### PR TITLE
Initial Docs creation

### LINKED ISSUE #14: Create function documentation
Determine best location to store function documentation (repo wiki?) and then build documentation.  Should probably use automation to build documentation based on powershell help info.

### PR DESCRIPTION
**Pull request by gjslavik**
Resolves #14.

Created "<root>\Docs" folder to house the function documentation. If/when we decide to create a super cool wiki page, it can link to that content.

The PlatyPS tool does not create documents for functions in the "private" folder, only the "public" folder.

### CODE REVIEW

**Review by thoen008 — APPROVED** [review]
Looks good. Never done mark up so can't really say if anything is wrong but I did see a couple things to improve on in the help files for the functions I worked on.

**Comment by gjslavik** [comment]
In PowerShell 7.x, there are a couple of cmdlets for interacting with markdown files. I used "Show-Markdown -Path <path to markdown file> -UseBrowser" and it allowed me to view the document in a browser. I also added the "Markdown All in One" extension to VSCode so they render in the preview panel.

**Review by jbolduan — CHANGES_REQUESTED** [review]
Can you delete and re-create using lower case directory names?  This will be a cluster fuck on case sensitive systems (Linux)

**Comment by gjslavik** [comment]
> Can you delete and re-create using lower case directory names? This will be a cluster fuck on case sensitive systems (Linux)
Done. Will this also impact the "UMN-AutoPackager" folder structure?

**Review by jbolduan — APPROVED** [review]
Looks good now.

**Pull request merged**
